# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 10
# Issues with these labels will never be considered stale
exemptLabels:
  - not stale
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been closed because it was stale for 15 days, and there was
  no further activity on it for 10 days. You can feel free to re-open it if
  the issue is important, and label it as "not stale."
