export default {
  state: {
    name: 'Alabama',
    state: 'AL',
    notes:
      'Negatives = (Totals - Positives) \nPositives occasionally update before totals do; do not revise negatives down, keep the last calculated negative.\nLast Updated (Local Time) = (current date + time = 00:00)',
    covid19Site:
      'https://alpublichealth.maps.arcgis.com/apps/opsdashboard/index.html#/6d2771faa9da4a2786a509d82c8cf0f7',
    covid19SiteSecondary: null,
    twitter: '@alpublichealth',
    stateData: {
      totalTestResults: 37890,
      state: 'AL',
      score: 3,
      grade: 'B',
      comprehensiveGrade: 'A+',
      dateModified: '2020-04-17T00:00:00-04:00',
      positive: 4572,
      negative: 33318,
      pending: null,
      hospitalizedCurrently: null,
      hospitalizedCumulative: 594,
      inIcuCurrently: null,
      inIcuCumulative: 247,
      recovered: null,
      onVentilatorCurrently: null,
      onVentilatorCumulative: 148,
      death: 151,
      childSlug: {
        slug: 'alabama',
      },
    },
  },
  stateData: {
    totalTestResults: 37890,
    state: 'AL',
    score: 3,
    grade: 'B',
    dateModified: '2020-04-17T00:00:00-04:00',
    positive: 4572,
    negative: 33318,
    pending: null,
    hospitalizedCurrently: null,
    hospitalizedCumulative: 594,
    inIcuCurrently: null,
    inIcuCumulative: 247,
    recovered: null,
    onVentilatorCurrently: null,
    onVentilatorCumulative: 148,
    death: 151,
  },
}
