name: Build
on: [workflow_dispatch]

env:
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
  CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
  GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
  GATSBY_ALGOLIA_INDEX_PREFIX: ${{ secrets.GATSBY_ALGOLIA_INDEX_PREFIX }}
  GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
  GATSBY_MAPBOX_API_TOKEN: ${{ secrets.GATSBY_MAPBOX_API_TOKEN }}


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12.20'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public