name: Jest tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12.20'
      - name: Install
        run: yarn install
      - name: Checkout API files
        run: yarn setup:api-repo
      - name: Jest tests
        run: yarn run test
      - name: Linting
        run: yarn run test:lint